version: '3.8'

services:
  gemini-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ~/.mozilla:/root/.mozilla:ro  # Mount Firefox profile for cookie extraction
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    restart: unless-stopped
    networks:
      - gemini-network

  gemini-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://gemini-api:8000/v1
    depends_on:
      - gemini-api
    restart: unless-stopped
    networks:
      - gemini-network

  gemini-tui:
    build:
      context: ./tui
      dockerfile: Dockerfile
    volumes:
      - ~/.mozilla:/root/.mozilla:ro  # Mount Firefox profile for cookie extraction
    environment:
      - API_URL=http://gemini-api:8000
    depends_on:
      - gemini-api
    restart: unless-stopped
    networks:
      - gemini-network

networks:
  gemini-network:
    driver: bridge

volumes:
  data:

